extractROIRespByConf3DMs_cr(project_params,which_subjects,[0,46,-7],'vmPFC');

extractROIRespByConf3DMs_cr(project_params,which_subjects,...
    'ROIs\union_FPl.nii','FPl');

extractROIRespByConf3DMs_cr(project_params,which_subjects,...
    'ROIs\union_FPm.nii','FPm');

extractROIRespByConf3DMs_cr(project_params,which_subjects,...
    'ROIs\union_46.nii','BA46');

extractROIRespByConf3DMs_cr(project_params,which_subjects,...
    'ROIs\preSMA.nii','preSMA');

extractROIRespByConf3DMs_cr(project_params,which_subjects,...
    'ROIs\rTPJ.nii','rTPJ');

extractROIRespByConf3DMs_cr(project_params,which_subjects,...
    'ROIs\rSTS.nii','rSTS');

extractROIRespByConf3DMs_cr(project_params,which_subjects,...
    'ROIs\insulaFromConfSqTaskF.nii','insula');