%  modelRDMs is a user-editable function which specifies the models which
%  brain-region RDMs should be compared to, and which specifies which kinds of
%  analysis should be performed.
%
%  Models should be stored in the "Models" struct as a single field labeled
%  with the model's name (use underscores in stead of spaces).
%  
%  Cai Wingfield 11-2009

function DM = modelRDMsForMultipleRegression()

conf_per_response = [0 1 0.5 0.5;...
    1 0 0.5 0.5;...
    0.5 0.5 0 1;...
    0.5 0.5 1 0];

cross_responses_conf = [0.5 0.5 0 1;...
    0.5 0.5 1 0;
    0 1 0.5 0.5;...
    1 0 0.5 0.5];

nothing = [0.5 0.5 0.5 0.5;...
    0.5 0.5 0.5 0.5;
    0.5 0.5 0.5 0.5;...
    0.5 0.5 0.5 0.5];

RDM1 = [conf_per_response, nothing, nothing; ...
    nothing, nothing, nothing; ...
    nothing, nothing, nothing];

RDM2 = [nothing, conf_per_response, nothing; ...
    nothing, nothing, nothing; ...
    nothing, nothing, nothing];

RDM3 = [nothing, nothing, conf_per_response; ...
    nothing, nothing, nothing; ...
    nothing, nothing, nothing];

RDM4 = [nothing, nothing, nothing; ...
    conf_per_response, nothing, nothing; ...
    nothing, nothing, nothing];

RDM5 = [nothing, nothing, nothing; ...
    nothing, conf_per_response, nothing; ...
    nothing, nothing, nothing];

RDM6 = [nothing, nothing, nothing; ...
    nothing, nothing, conf_per_response; ...
    nothing, nothing, nothing];

RDM7 = [nothing, nothing, nothing; ...
    nothing, nothing, nothing; ...
    conf_per_response, nothing, nothing];

RDM8 = [nothing, nothing, nothing; ...
    nothing, nothing, nothing; ...
    nothing, conf_per_response, nothing];

RDM9 = [nothing, nothing, nothing; ...
    nothing, nothing, nothing; ...
    nothing, nothing, conf_per_response];

RDM10 = [cross_responses_conf, nothing, nothing; ...
    nothing, nothing, nothing; ...
    nothing, nothing, nothing];

RDM11 = [nothing, cross_responses_conf, nothing; ...
    nothing, nothing, nothing; ...
    nothing, nothing, nothing];

RDM12 = [nothing, nothing, cross_responses_conf; ...
    nothing, nothing, nothing; ...
    nothing, nothing, nothing];

RDM13 = [nothing, nothing, nothing; ...
    cross_responses_conf, nothing, nothing; ...
    nothing, nothing, nothing];

RDM14 = [nothing, nothing, nothing; ...
    nothing, cross_responses_conf, nothing; ...
    nothing, nothing, nothing];

RDM15 = [nothing, nothing, nothing; ...
    nothing, nothing, cross_responses_conf; ...
    nothing, nothing, nothing];

RDM16 = [nothing, nothing, nothing; ...
    nothing, nothing, nothing; ...
    cross_responses_conf, nothing, nothing];

RDM17 = [nothing, nothing, nothing; ...
    nothing, nothing, nothing; ...
    nothing, cross_responses_conf, nothing];

RDM18 = [nothing, nothing, nothing; ...
    nothing, nothing, nothing; ...
    nothing, nothing, cross_responses_conf];

RDM19 = ones(12,12);

DM = [RDM1(:), RDM2(:), RDM3(:), RDM4(:), RDM5(:), RDM6(:), RDM7(:), ...
    RDM8(:), RDM9(:), RDM10(:), RDM11(:), RDM12(:), RDM13(:), RDM14(:), ...
    RDM15(:), RDM16(:), RDM17(:), RDM18(:), RDM19(:)];



end
